# Generated by Django 2.0.3 on 2018-03-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180318_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='title_image',
        ),
    ]
