# Generated by Django 2.0.3 on 2018-03-14 13:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='hero_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
