# Generated by Django 2.0.3 on 2018-03-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180314_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='hero_text',
            field=models.TextField(blank=True),
        ),
    ]
